name: xarrayutils-docs
dependencies:
  - python=3.6
  - future
  - pytest
  - numpydoc
  - sphinx
  - sphinx_rtd_theme
  - ipykernel
  # Packages which are needed to execute your examples
  # These will vary
  - black
  - ipython
  - jupyter
  - matplotlib
  - xarray
  - netcdf4
  - nc-time-axis
  - astropy
  - dask < 2.0 # remove later
  - numpy
  - xgcm
  - scipy
  - cartopy
  - gsw # remove once dependencies are optional (https://github.com/jbusecke/xarrayutils/issues/38)
  - pip
 #
  - pip:
    - docrep
    - nbsphinx
    - jupyter_client
    # - jupyter-sphinx # not sure what this adds...
