name: test_env_xarrayutils
channels:
  - conda-forge
dependencies:
  - python=3.8
  - xarray
  - dask < 2 #remove this once upstream problem
             # (https://github.com/pydata/xarray/issues/3574) is fixed
  - numpy
  - pytest
  - future
  - scipy
  - black
  - astropy
  - matplotlib
  # Necesary additions for the plotting tools (might have to make thos optional)
  - gsw
  - cartopy
  - xgcm
  - pip:
    - codecov
    - pytest-cov
