name: test_env
channels:
  - conda-forge
dependencies:
  - python=3.6
  - xarray
  - dask
  - numpy
  - pytest
  - future
  - scipy
  - flake8
  - astropy
  - matplotlib
  # Necesary additions for the plotting tools (might have to make thos optional)
  # - gsw # remove here to check missing gsw in ci
  - cartopy
  - xgcm
  - pip:
    - codecov
    - pytest-cov
