name: test_env_xarrayutils
channels:
  - conda-forge
dependencies:
  - python=3.6
  - xarray  # < 0.12 # this worked to restore the apply_ufunc stuff
  - dask < 2.0
  - numpy # < 1.14 # this worked to restore the apply_ufunc stuff
  - pytest
  - future
  - scipy
  - black
  - astropy
  - matplotlib
  # Necesary additions for the plotting tools (might have to make thos optional)
  - gsw
  - cartopy
  - xgcm
  - pip:
    - codecov
    - pytest-cov
